### ISSUE TITLE
Clean dependencies

### ISSUE THREAD

**Issue by airibarne** [dribia/driviz#29]
We have dependencies in the main group that are not explicitly used in the main package, right?

- NumPy
- Pandas
- Rich
- Typer

We should leave there only those that are really necessary for our functionality.

**Comment by hribera** [comment]
@airibarne L'únic lloc on es fan servir `numpy` i `pandas` és en un exemple de codi als docstrings:
```
This theme uses Google's
`Roboto <https://fonts.google.com/specimen/Roboto>`_ font,
**it should be installed in your OS**.
You can install it in Ubuntu with:

.. code-block:: console

    $ sudo apt install fonts-roboto

The following example generates the interactive plot
``data/results/altair_example_barh.html``:

.. doctest::

    >>> import altair as alt
    >>> import numpy as np
    >>> import pandas as pd
    >>> import random

    >>> from driviz import theme

    >>> theme.enable()
```

Entenc que no és problema treure la dependència si només és aquí?

**Comment by mauro-dribia** [comment]
> @airibarne L'únic lloc on es fan servir `numpy` i `pandas` és en un exemple de codi als docstrings:
> 
> ```
> This theme uses Google's
> `Roboto <https://fonts.google.com/specimen/Roboto>`_ font,
> **it should be installed in your OS**.
> You can install it in Ubuntu with:
> 
> .. code-block:: console
> 
>     $ sudo apt install fonts-roboto
> 
> The following example generates the interactive plot
> ``data/results/altair_example_barh.html``:
> 
> .. doctest::
> 
>     >>> import altair as alt
>     >>> import numpy as np
>     >>> import pandas as pd
>     >>> import random
> 
>     >>> from driviz import theme
> 
>     >>> theme.enable()
> ```
> 
> Entenc que no és problema treure la dependència si només és aquí?

Puede que nos falte una action que revise los codeblocks, no?

**Comment by airibarne** [comment]
> > @airibarne L'únic lloc on es fan servir `numpy` i `pandas` és en un exemple de codi als docstrings:
> > ```
> > This theme uses Google's
> > `Roboto <https://fonts.google.com/specimen/Roboto>`_ font,
> > **it should be installed in your OS**.
> > You can install it in Ubuntu with:
> > 
> > .. code-block:: console
> > 
> >     $ sudo apt install fonts-roboto
> > 
> > The following example generates the interactive plot
> > ``data/results/altair_example_barh.html``:
> > 
> > .. doctest::
> > 
> >     >>> import altair as alt
> >     >>> import numpy as np
> >     >>> import pandas as pd
> >     >>> import random
> > 
> >     >>> from driviz import theme
> > 
> >     >>> theme.enable()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Entenc que no és problema treure la dependència si només és aquí?
> 
> Puede que nos falte una action que revise los codeblocks, no?

Esto era lo que hacían los doctests, no? :rofl:

**Comment by mauro-dribia** [comment]
> > > @airibarne L'únic lloc on es fan servir `numpy` i `pandas` és en un exemple de codi als docstrings:
> > > ```
> > > This theme uses Google's
> > > `Roboto <https://fonts.google.com/specimen/Roboto>`_ font,
> > > **it should be installed in your OS**.
> > > You can install it in Ubuntu with:
> > > 
> > > .. code-block:: console
> > > 
> > >     $ sudo apt install fonts-roboto
> > > 
> > > The following example generates the interactive plot
> > > ``data/results/altair_example_barh.html``:
> > > 
> > > .. doctest::
> > > 
> > >     >>> import altair as alt
> > >     >>> import numpy as np
> > >     >>> import pandas as pd
> > >     >>> import random
> > > 
> > >     >>> from driviz import theme
> > > 
> > >     >>> theme.enable()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Entenc que no és problema treure la dependència si només és aquí?
> > 
> > 
> > Puede que nos falte una action que revise los codeblocks, no?
> 
> Esto era lo que hacían los doctests, no? 🤣

Bueno, en este repo no lo tenemos implementado... tendríamos que agregar toda una carpeta de sphinx a docs para poder ejecutarlos, no?

**Comment by airibarne** [comment]
Nono, doctest es standard module!! https://docs.python.org/3/library/doctest.html
